### ISSUE TITLE
No longer works with latest Inkscape (1.3)

### ISSUE THREAD

**Issue by roel-v** [fsmMLK/inkscapeDimensions#20]
Out of the box, the 'Dimensions' entry in the fsmMLK submenu is greyed out. I fixed that (and a few other issues) before I started getting so deep in that I didn't really know what I was doing any more:

- in inkscapeDimensions.inx, there is a dependency on inkex.py coded in. The extensions-errors.log showed that a dependency couldn't be loaded. Just commenting out that line made the entry no longer be greyed out. It seems modern Inkscape versions include that file in the Python installation directory? At least I can import it just fine from the command line. So that seems to be no longer needed.
- Then I got a deprecation warning about OptionsParser. In Dimensions.__init__(), I had to change all OptionsParser.[something, forgot what it was called] to arg_parser.add_argument.
- Then I got a message about string not being callable. I had to change the type option to add_argument from string to the actual type, e.g. "string" to str, "float" to float etc.

That's when I gave up, I got errors about there being too many arguments to unpack for inkDraw.color.parseColorPicker() but that required me to understand too much of the internal API. Is this still maintained?

**Comment by fsmMLK** [comment]
Hi, thanks for your message. I will take a look at this issue ASAP. I did not know that inkscape 1.3 had such big changes.

**Comment by fsmMLK** [comment]
It seems the latest version is working just fine in my machine with inskscape 1.3.2. 

The lastest version does not have any inkex.py depencency, but the legacy version does. Did you install the 'latest' version?

**Comment by roel-v** [comment]
You're right, I used the wrong version for inkscapeDimensions and only got the correct one for inkscapeMadeEasy . It works now! Apologies!
